// <auto-generated>

#nullable enable

using System.Text.Json;

namespace EdFi.OdsApi.Sdk.v73.Client
{
    /// <summary>
    /// Provides the JsonSerializerOptions
    /// </summary>
    public class JsonSerializerOptionsProvider
    {
        /// <summary>
        /// the JsonSerializerOptions
        /// </summary>
        public JsonSerializerOptions Options { get; }

        /// <summary>
        /// Instantiates a JsonSerializerOptionsProvider
        /// </summary>
        public JsonSerializerOptionsProvider(JsonSerializerOptions options)
        {
            Options = options;
        }
    }
}