/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiStudentAssessmentRegistrationAssessmentCustomization
    /// </summary>
    [DataContract(Name = "edFi_studentAssessmentRegistrationAssessmentCustomization")]
    public partial class EdFiStudentAssessmentRegistrationAssessmentCustomization : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAssessmentRegistrationAssessmentCustomization" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiStudentAssessmentRegistrationAssessmentCustomization() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAssessmentRegistrationAssessmentCustomization" /> class.
        /// </summary>
        /// <param name="customizationKey">An agreed upon identifier for the custom information. (required).</param>
        /// <param name="customizationValue">Custom value for the indicated CustomizationKey. (required).</param>
        /// <param name="ext">Extensions to the StudentAssessmentRegistrationAssessmentCustomization entity..</param>
        public EdFiStudentAssessmentRegistrationAssessmentCustomization(string customizationKey = default, string customizationValue = default, Object ext = default)
        {
            // to ensure "customizationKey" is required (not null)
            if (customizationKey == null)
            {
                throw new ArgumentNullException("customizationKey is a required property for EdFiStudentAssessmentRegistrationAssessmentCustomization and cannot be null");
            }
            this.CustomizationKey = customizationKey;
            // to ensure "customizationValue" is required (not null)
            if (customizationValue == null)
            {
                throw new ArgumentNullException("customizationValue is a required property for EdFiStudentAssessmentRegistrationAssessmentCustomization and cannot be null");
            }
            this.CustomizationValue = customizationValue;
            this.Ext = ext;
        }

        /// <summary>
        /// An agreed upon identifier for the custom information.
        /// </summary>
        /// <value>An agreed upon identifier for the custom information.</value>
        [DataMember(Name = "customizationKey", IsRequired = true, EmitDefaultValue = true)]
        public string CustomizationKey { get; set; }

        /// <summary>
        /// Custom value for the indicated CustomizationKey.
        /// </summary>
        /// <value>Custom value for the indicated CustomizationKey.</value>
        [DataMember(Name = "customizationValue", IsRequired = true, EmitDefaultValue = true)]
        public string CustomizationValue { get; set; }

        /// <summary>
        /// Extensions to the StudentAssessmentRegistrationAssessmentCustomization entity.
        /// </summary>
        /// <value>Extensions to the StudentAssessmentRegistrationAssessmentCustomization entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentAssessmentRegistrationAssessmentCustomization {\n");
            sb.Append("  CustomizationKey: ").Append(CustomizationKey).Append("\n");
            sb.Append("  CustomizationValue: ").Append(CustomizationValue).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CustomizationKey (string) maxLength
            if (this.CustomizationKey != null && this.CustomizationKey.Length > 60)
            {
                yield return new ValidationResult("Invalid value for CustomizationKey, length must be less than 60.", new [] { "CustomizationKey" });
            }

            // CustomizationValue (string) maxLength
            if (this.CustomizationValue != null && this.CustomizationValue.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for CustomizationValue, length must be less than 1024.", new [] { "CustomizationValue" });
            }

            yield break;
        }
    }

}
