// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v73.Client;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiStudentAssessmentReference
    /// </summary>
    public partial class EdFiStudentAssessmentReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAssessmentReference" /> class.
        /// </summary>
        /// <param name="assessmentIdentifier">A unique number or alphanumeric code assigned to an assessment.</param>
        /// <param name="namespace">Namespace for the assessment.</param>
        /// <param name="studentAssessmentIdentifier">A unique number or alphanumeric code assigned to an assessment administered to a student.</param>
        /// <param name="studentUniqueId">A unique alphanumeric code assigned to a student.</param>
        /// <param name="link">link</param>
        [JsonConstructor]
        public EdFiStudentAssessmentReference(string assessmentIdentifier, string @namespace, string studentAssessmentIdentifier, string studentUniqueId, Option<Link?> link = default)
        {
            AssessmentIdentifier = assessmentIdentifier;
            Namespace = @namespace;
            StudentAssessmentIdentifier = studentAssessmentIdentifier;
            StudentUniqueId = studentUniqueId;
            LinkOption = link;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// A unique number or alphanumeric code assigned to an assessment.
        /// </summary>
        /// <value>A unique number or alphanumeric code assigned to an assessment.</value>
        [JsonPropertyName("assessmentIdentifier")]
        public string AssessmentIdentifier { get; set; }

        /// <summary>
        /// Namespace for the assessment.
        /// </summary>
        /// <value>Namespace for the assessment.</value>
        [JsonPropertyName("namespace")]
        public string Namespace { get; set; }

        /// <summary>
        /// A unique number or alphanumeric code assigned to an assessment administered to a student.
        /// </summary>
        /// <value>A unique number or alphanumeric code assigned to an assessment administered to a student.</value>
        [JsonPropertyName("studentAssessmentIdentifier")]
        public string StudentAssessmentIdentifier { get; set; }

        /// <summary>
        /// A unique alphanumeric code assigned to a student.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a student.</value>
        [JsonPropertyName("studentUniqueId")]
        public string StudentUniqueId { get; set; }

        /// <summary>
        /// Used to track the state of Link
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Link?> LinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [JsonPropertyName("link")]
        public Link? Link { get { return this.LinkOption; } set { this.LinkOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentAssessmentReference {\n");
            sb.Append("  AssessmentIdentifier: ").Append(AssessmentIdentifier).Append("\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  StudentAssessmentIdentifier: ").Append(StudentAssessmentIdentifier).Append("\n");
            sb.Append("  StudentUniqueId: ").Append(StudentUniqueId).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AssessmentIdentifier (string) maxLength
            if (this.AssessmentIdentifier != null && this.AssessmentIdentifier.Length > 60)
            {
                yield return new ValidationResult("Invalid value for AssessmentIdentifier, length must be less than 60.", new [] { "AssessmentIdentifier" });
            }

            // Namespace (string) maxLength
            if (this.Namespace != null && this.Namespace.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be less than 255.", new [] { "Namespace" });
            }

            // Namespace (string) minLength
            if (this.Namespace != null && this.Namespace.Length < 5)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be greater than 5.", new [] { "Namespace" });
            }

            // StudentAssessmentIdentifier (string) maxLength
            if (this.StudentAssessmentIdentifier != null && this.StudentAssessmentIdentifier.Length > 60)
            {
                yield return new ValidationResult("Invalid value for StudentAssessmentIdentifier, length must be less than 60.", new [] { "StudentAssessmentIdentifier" });
            }

            // StudentUniqueId (string) maxLength
            if (this.StudentUniqueId != null && this.StudentUniqueId.Length > 32)
            {
                yield return new ValidationResult("Invalid value for StudentUniqueId, length must be less than 32.", new [] { "StudentUniqueId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiStudentAssessmentReference" />
    /// </summary>
    public class EdFiStudentAssessmentReferenceJsonConverter : JsonConverter<EdFiStudentAssessmentReference>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiStudentAssessmentReference" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiStudentAssessmentReference Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> assessmentIdentifier = default;
            Option<string?> varNamespace = default;
            Option<string?> studentAssessmentIdentifier = default;
            Option<string?> studentUniqueId = default;
            Option<Link?> link = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "assessmentIdentifier":
                            assessmentIdentifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "namespace":
                            varNamespace = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "studentAssessmentIdentifier":
                            studentAssessmentIdentifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "studentUniqueId":
                            studentUniqueId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "link":
                            link = new Option<Link?>(JsonSerializer.Deserialize<Link>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assessmentIdentifier.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAssessmentReference.", nameof(assessmentIdentifier));

            if (!varNamespace.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAssessmentReference.", nameof(varNamespace));

            if (!studentAssessmentIdentifier.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAssessmentReference.", nameof(studentAssessmentIdentifier));

            if (!studentUniqueId.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAssessmentReference.", nameof(studentUniqueId));

            if (assessmentIdentifier.IsSet && assessmentIdentifier.Value == null)
                throw new ArgumentNullException(nameof(assessmentIdentifier), "Property is not nullable for class EdFiStudentAssessmentReference.");

            if (varNamespace.IsSet && varNamespace.Value == null)
                throw new ArgumentNullException(nameof(varNamespace), "Property is not nullable for class EdFiStudentAssessmentReference.");

            if (studentAssessmentIdentifier.IsSet && studentAssessmentIdentifier.Value == null)
                throw new ArgumentNullException(nameof(studentAssessmentIdentifier), "Property is not nullable for class EdFiStudentAssessmentReference.");

            if (studentUniqueId.IsSet && studentUniqueId.Value == null)
                throw new ArgumentNullException(nameof(studentUniqueId), "Property is not nullable for class EdFiStudentAssessmentReference.");

            if (link.IsSet && link.Value == null)
                throw new ArgumentNullException(nameof(link), "Property is not nullable for class EdFiStudentAssessmentReference.");

            return new EdFiStudentAssessmentReference(assessmentIdentifier.Value!, varNamespace.Value!, studentAssessmentIdentifier.Value!, studentUniqueId.Value!, link);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiStudentAssessmentReference" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentAssessmentReference"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiStudentAssessmentReference edFiStudentAssessmentReference, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiStudentAssessmentReference, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiStudentAssessmentReference" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentAssessmentReference"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiStudentAssessmentReference edFiStudentAssessmentReference, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiStudentAssessmentReference.AssessmentIdentifier == null)
                throw new ArgumentNullException(nameof(edFiStudentAssessmentReference.AssessmentIdentifier), "Property is required for class EdFiStudentAssessmentReference.");

            if (edFiStudentAssessmentReference.Namespace == null)
                throw new ArgumentNullException(nameof(edFiStudentAssessmentReference.Namespace), "Property is required for class EdFiStudentAssessmentReference.");

            if (edFiStudentAssessmentReference.StudentAssessmentIdentifier == null)
                throw new ArgumentNullException(nameof(edFiStudentAssessmentReference.StudentAssessmentIdentifier), "Property is required for class EdFiStudentAssessmentReference.");

            if (edFiStudentAssessmentReference.StudentUniqueId == null)
                throw new ArgumentNullException(nameof(edFiStudentAssessmentReference.StudentUniqueId), "Property is required for class EdFiStudentAssessmentReference.");

            if (edFiStudentAssessmentReference.LinkOption.IsSet && edFiStudentAssessmentReference.Link == null)
                throw new ArgumentNullException(nameof(edFiStudentAssessmentReference.Link), "Property is required for class EdFiStudentAssessmentReference.");

            writer.WriteString("assessmentIdentifier", edFiStudentAssessmentReference.AssessmentIdentifier);

            writer.WriteString("namespace", edFiStudentAssessmentReference.Namespace);

            writer.WriteString("studentAssessmentIdentifier", edFiStudentAssessmentReference.StudentAssessmentIdentifier);

            writer.WriteString("studentUniqueId", edFiStudentAssessmentReference.StudentUniqueId);

            if (edFiStudentAssessmentReference.LinkOption.IsSet)
            {
                writer.WritePropertyName("link");
                JsonSerializer.Serialize(writer, edFiStudentAssessmentReference.Link, jsonSerializerOptions);
            }
        }
    }
}
