/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiEducationOrganizationCategory
    /// </summary>
    [DataContract(Name = "edFi_educationOrganizationCategory")]
    public partial class EdFiEducationOrganizationCategory : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiEducationOrganizationCategory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiEducationOrganizationCategory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiEducationOrganizationCategory" /> class.
        /// </summary>
        /// <param name="educationOrganizationCategoryDescriptor">The classification of the education agency within the geographic boundaries of a state according to the level of administrative and operational control granted by the state. (required).</param>
        /// <param name="ext">Extensions to the EducationOrganizationCategory entity..</param>
        public EdFiEducationOrganizationCategory(string educationOrganizationCategoryDescriptor = default, Object ext = default)
        {
            // to ensure "educationOrganizationCategoryDescriptor" is required (not null)
            if (educationOrganizationCategoryDescriptor == null)
            {
                throw new ArgumentNullException("educationOrganizationCategoryDescriptor is a required property for EdFiEducationOrganizationCategory and cannot be null");
            }
            this.EducationOrganizationCategoryDescriptor = educationOrganizationCategoryDescriptor;
            this.Ext = ext;
        }

        /// <summary>
        /// The classification of the education agency within the geographic boundaries of a state according to the level of administrative and operational control granted by the state.
        /// </summary>
        /// <value>The classification of the education agency within the geographic boundaries of a state according to the level of administrative and operational control granted by the state.</value>
        [DataMember(Name = "educationOrganizationCategoryDescriptor", IsRequired = true, EmitDefaultValue = true)]
        public string EducationOrganizationCategoryDescriptor { get; set; }

        /// <summary>
        /// Extensions to the EducationOrganizationCategory entity.
        /// </summary>
        /// <value>Extensions to the EducationOrganizationCategory entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiEducationOrganizationCategory {\n");
            sb.Append("  EducationOrganizationCategoryDescriptor: ").Append(EducationOrganizationCategoryDescriptor).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EducationOrganizationCategoryDescriptor (string) maxLength
            if (this.EducationOrganizationCategoryDescriptor != null && this.EducationOrganizationCategoryDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for EducationOrganizationCategoryDescriptor, length must be less than 306.", new [] { "EducationOrganizationCategoryDescriptor" });
            }

            yield break;
        }
    }

}
