/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation
    /// </summary>
    [DataContract(Name = "edFi_studentSpecialEducationProgramAssociationDisabilityDesignation")]
    public partial class EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation" /> class.
        /// </summary>
        /// <param name="disabilityDesignationDescriptor">Whether the disability is IDEA, Section 504, or other disability designation. (required).</param>
        /// <param name="ext">Extensions to the StudentSpecialEducationProgramAssociationDisabilityDesignation entity..</param>
        public EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation(string disabilityDesignationDescriptor = default, Object ext = default)
        {
            // to ensure "disabilityDesignationDescriptor" is required (not null)
            if (disabilityDesignationDescriptor == null)
            {
                throw new ArgumentNullException("disabilityDesignationDescriptor is a required property for EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation and cannot be null");
            }
            this.DisabilityDesignationDescriptor = disabilityDesignationDescriptor;
            this.Ext = ext;
        }

        /// <summary>
        /// Whether the disability is IDEA, Section 504, or other disability designation.
        /// </summary>
        /// <value>Whether the disability is IDEA, Section 504, or other disability designation.</value>
        [DataMember(Name = "disabilityDesignationDescriptor", IsRequired = true, EmitDefaultValue = true)]
        public string DisabilityDesignationDescriptor { get; set; }

        /// <summary>
        /// Extensions to the StudentSpecialEducationProgramAssociationDisabilityDesignation entity.
        /// </summary>
        /// <value>Extensions to the StudentSpecialEducationProgramAssociationDisabilityDesignation entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentSpecialEducationProgramAssociationDisabilityDesignation {\n");
            sb.Append("  DisabilityDesignationDescriptor: ").Append(DisabilityDesignationDescriptor).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisabilityDesignationDescriptor (string) maxLength
            if (this.DisabilityDesignationDescriptor != null && this.DisabilityDesignationDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for DisabilityDesignationDescriptor, length must be less than 306.", new [] { "DisabilityDesignationDescriptor" });
            }

            yield break;
        }
    }

}
