// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v73.Client;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiStudentProgramEvaluationStudentEvaluationObjective
    /// </summary>
    public partial class EdFiStudentProgramEvaluationStudentEvaluationObjective : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentProgramEvaluationStudentEvaluationObjective" /> class.
        /// </summary>
        /// <param name="programEvaluationObjectiveReference">programEvaluationObjectiveReference</param>
        /// <param name="evaluationObjectiveRatingLevelDescriptor">The rating level achieved based upon the rating or score for the evaluation objective.</param>
        /// <param name="evaluationObjectiveNumericRating">The numerical rating or score for the evaluation objective.</param>
        /// <param name="ext">Extensions to the StudentProgramEvaluationStudentEvaluationObjective entity.</param>
        [JsonConstructor]
        public EdFiStudentProgramEvaluationStudentEvaluationObjective(EdFiProgramEvaluationObjectiveReference programEvaluationObjectiveReference, Option<string?> evaluationObjectiveRatingLevelDescriptor = default, Option<double?> evaluationObjectiveNumericRating = default, Option<Object?> ext = default)
        {
            ProgramEvaluationObjectiveReference = programEvaluationObjectiveReference;
            EvaluationObjectiveRatingLevelDescriptorOption = evaluationObjectiveRatingLevelDescriptor;
            EvaluationObjectiveNumericRatingOption = evaluationObjectiveNumericRating;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProgramEvaluationObjectiveReference
        /// </summary>
        [JsonPropertyName("programEvaluationObjectiveReference")]
        public EdFiProgramEvaluationObjectiveReference ProgramEvaluationObjectiveReference { get; set; }

        /// <summary>
        /// Used to track the state of EvaluationObjectiveRatingLevelDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EvaluationObjectiveRatingLevelDescriptorOption { get; private set; }

        /// <summary>
        /// The rating level achieved based upon the rating or score for the evaluation objective.
        /// </summary>
        /// <value>The rating level achieved based upon the rating or score for the evaluation objective.</value>
        [JsonPropertyName("evaluationObjectiveRatingLevelDescriptor")]
        public string? EvaluationObjectiveRatingLevelDescriptor { get { return this.EvaluationObjectiveRatingLevelDescriptorOption; } set { this.EvaluationObjectiveRatingLevelDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EvaluationObjectiveNumericRating
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> EvaluationObjectiveNumericRatingOption { get; private set; }

        /// <summary>
        /// The numerical rating or score for the evaluation objective.
        /// </summary>
        /// <value>The numerical rating or score for the evaluation objective.</value>
        [JsonPropertyName("evaluationObjectiveNumericRating")]
        public double? EvaluationObjectiveNumericRating { get { return this.EvaluationObjectiveNumericRatingOption; } set { this.EvaluationObjectiveNumericRatingOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the StudentProgramEvaluationStudentEvaluationObjective entity.
        /// </summary>
        /// <value>Extensions to the StudentProgramEvaluationStudentEvaluationObjective entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentProgramEvaluationStudentEvaluationObjective {\n");
            sb.Append("  ProgramEvaluationObjectiveReference: ").Append(ProgramEvaluationObjectiveReference).Append("\n");
            sb.Append("  EvaluationObjectiveRatingLevelDescriptor: ").Append(EvaluationObjectiveRatingLevelDescriptor).Append("\n");
            sb.Append("  EvaluationObjectiveNumericRating: ").Append(EvaluationObjectiveNumericRating).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EvaluationObjectiveRatingLevelDescriptor (string) maxLength
            if (this.EvaluationObjectiveRatingLevelDescriptor != null && this.EvaluationObjectiveRatingLevelDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for EvaluationObjectiveRatingLevelDescriptor, length must be less than 306.", new [] { "EvaluationObjectiveRatingLevelDescriptor" });
            }

            // EvaluationObjectiveNumericRating (double) maximum
            if (this.EvaluationObjectiveNumericRatingOption.IsSet && this.EvaluationObjectiveNumericRatingOption.Value > (double)999.999)
            {
                yield return new ValidationResult("Invalid value for EvaluationObjectiveNumericRating, must be a value less than or equal to 999.999.", new [] { "EvaluationObjectiveNumericRating" });
            }

            // EvaluationObjectiveNumericRating (double) minimum
            if (this.EvaluationObjectiveNumericRatingOption.IsSet && this.EvaluationObjectiveNumericRatingOption.Value < (double)-999.999)
            {
                yield return new ValidationResult("Invalid value for EvaluationObjectiveNumericRating, must be a value greater than or equal to -999.999.", new [] { "EvaluationObjectiveNumericRating" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiStudentProgramEvaluationStudentEvaluationObjective" />
    /// </summary>
    public class EdFiStudentProgramEvaluationStudentEvaluationObjectiveJsonConverter : JsonConverter<EdFiStudentProgramEvaluationStudentEvaluationObjective>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiStudentProgramEvaluationStudentEvaluationObjective" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiStudentProgramEvaluationStudentEvaluationObjective Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EdFiProgramEvaluationObjectiveReference?> programEvaluationObjectiveReference = default;
            Option<string?> evaluationObjectiveRatingLevelDescriptor = default;
            Option<double?> evaluationObjectiveNumericRating = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "programEvaluationObjectiveReference":
                            programEvaluationObjectiveReference = new Option<EdFiProgramEvaluationObjectiveReference?>(JsonSerializer.Deserialize<EdFiProgramEvaluationObjectiveReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "evaluationObjectiveRatingLevelDescriptor":
                            evaluationObjectiveRatingLevelDescriptor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "evaluationObjectiveNumericRating":
                            evaluationObjectiveNumericRating = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!programEvaluationObjectiveReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentProgramEvaluationStudentEvaluationObjective.", nameof(programEvaluationObjectiveReference));

            if (programEvaluationObjectiveReference.IsSet && programEvaluationObjectiveReference.Value == null)
                throw new ArgumentNullException(nameof(programEvaluationObjectiveReference), "Property is not nullable for class EdFiStudentProgramEvaluationStudentEvaluationObjective.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiStudentProgramEvaluationStudentEvaluationObjective.");

            return new EdFiStudentProgramEvaluationStudentEvaluationObjective(programEvaluationObjectiveReference.Value!, evaluationObjectiveRatingLevelDescriptor, evaluationObjectiveNumericRating, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiStudentProgramEvaluationStudentEvaluationObjective" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentProgramEvaluationStudentEvaluationObjective"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiStudentProgramEvaluationStudentEvaluationObjective edFiStudentProgramEvaluationStudentEvaluationObjective, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiStudentProgramEvaluationStudentEvaluationObjective, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiStudentProgramEvaluationStudentEvaluationObjective" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentProgramEvaluationStudentEvaluationObjective"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiStudentProgramEvaluationStudentEvaluationObjective edFiStudentProgramEvaluationStudentEvaluationObjective, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiStudentProgramEvaluationStudentEvaluationObjective.ProgramEvaluationObjectiveReference == null)
                throw new ArgumentNullException(nameof(edFiStudentProgramEvaluationStudentEvaluationObjective.ProgramEvaluationObjectiveReference), "Property is required for class EdFiStudentProgramEvaluationStudentEvaluationObjective.");

            if (edFiStudentProgramEvaluationStudentEvaluationObjective.ExtOption.IsSet && edFiStudentProgramEvaluationStudentEvaluationObjective.Ext == null)
                throw new ArgumentNullException(nameof(edFiStudentProgramEvaluationStudentEvaluationObjective.Ext), "Property is required for class EdFiStudentProgramEvaluationStudentEvaluationObjective.");

            writer.WritePropertyName("programEvaluationObjectiveReference");
            JsonSerializer.Serialize(writer, edFiStudentProgramEvaluationStudentEvaluationObjective.ProgramEvaluationObjectiveReference, jsonSerializerOptions);
            if (edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveRatingLevelDescriptorOption.IsSet)
                if (edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveRatingLevelDescriptorOption.Value != null)
                    writer.WriteString("evaluationObjectiveRatingLevelDescriptor", edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveRatingLevelDescriptor);
                else
                    writer.WriteNull("evaluationObjectiveRatingLevelDescriptor");

            if (edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveNumericRatingOption.IsSet)
                if (edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveNumericRatingOption.Value != null)
                    writer.WriteNumber("evaluationObjectiveNumericRating", edFiStudentProgramEvaluationStudentEvaluationObjective.EvaluationObjectiveNumericRatingOption.Value!.Value);
                else
                    writer.WriteNull("evaluationObjectiveNumericRating");

            if (edFiStudentProgramEvaluationStudentEvaluationObjective.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiStudentProgramEvaluationStudentEvaluationObjective.Ext, jsonSerializerOptions);
            }
        }
    }
}
