/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiContactReference
    /// </summary>
    [DataContract(Name = "edFi_contactReference")]
    public partial class EdFiContactReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiContactReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiContactReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiContactReference" /> class.
        /// </summary>
        /// <param name="contactUniqueId">A unique alphanumeric code assigned to a contact. (required).</param>
        /// <param name="link">link.</param>
        public EdFiContactReference(string contactUniqueId = default, Link link = default)
        {
            // to ensure "contactUniqueId" is required (not null)
            if (contactUniqueId == null)
            {
                throw new ArgumentNullException("contactUniqueId is a required property for EdFiContactReference and cannot be null");
            }
            this.ContactUniqueId = contactUniqueId;
            this.Link = link;
        }

        /// <summary>
        /// A unique alphanumeric code assigned to a contact.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a contact.</value>
        [DataMember(Name = "contactUniqueId", IsRequired = true, EmitDefaultValue = true)]
        public string ContactUniqueId { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public Link Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiContactReference {\n");
            sb.Append("  ContactUniqueId: ").Append(ContactUniqueId).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ContactUniqueId (string) maxLength
            if (this.ContactUniqueId != null && this.ContactUniqueId.Length > 32)
            {
                yield return new ValidationResult("Invalid value for ContactUniqueId, length must be less than 32.", new [] { "ContactUniqueId" });
            }

            yield break;
        }
    }

}
