/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// EdFiStudentTransportation
    /// </summary>
    [DataContract(Name = "edFi_studentTransportation")]
    public partial class EdFiStudentTransportation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentTransportation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiStudentTransportation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentTransportation" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="studentReference">studentReference (required).</param>
        /// <param name="transportationEducationOrganizationReference">transportationEducationOrganizationReference (required).</param>
        /// <param name="specialAccomodationRequirements">Specific requirements needed to accommodate a student&#39;s physical needs which may include special equipment installed in a vehicle or a special arrangement for transportation..</param>
        /// <param name="studentBusDetails">studentBusDetails.</param>
        /// <param name="transportationPublicExpenseEligibilityTypeDescriptor">The primary type of eligibility for transporting a student at public expense..</param>
        /// <param name="transportationTypeDescriptor">The mode or type of transportation utilized by a student to commute to and from school.</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        /// <param name="lastModifiedDate">The date and time the resource was last modified..</param>
        /// <param name="ext">Extensions to the StudentTransportation entity..</param>
        public EdFiStudentTransportation(string id = default, EdFiStudentReference studentReference = default, EdFiEducationOrganizationReference transportationEducationOrganizationReference = default, string specialAccomodationRequirements = default, EdFiStudentTransportationStudentBusDetails studentBusDetails = default, string transportationPublicExpenseEligibilityTypeDescriptor = default, string transportationTypeDescriptor = default, string etag = default, DateTime lastModifiedDate = default, Object ext = default)
        {
            // to ensure "studentReference" is required (not null)
            if (studentReference == null)
            {
                throw new ArgumentNullException("studentReference is a required property for EdFiStudentTransportation and cannot be null");
            }
            this.StudentReference = studentReference;
            // to ensure "transportationEducationOrganizationReference" is required (not null)
            if (transportationEducationOrganizationReference == null)
            {
                throw new ArgumentNullException("transportationEducationOrganizationReference is a required property for EdFiStudentTransportation and cannot be null");
            }
            this.TransportationEducationOrganizationReference = transportationEducationOrganizationReference;
            this.Id = id;
            this.SpecialAccomodationRequirements = specialAccomodationRequirements;
            this.StudentBusDetails = studentBusDetails;
            this.TransportationPublicExpenseEligibilityTypeDescriptor = transportationPublicExpenseEligibilityTypeDescriptor;
            this.TransportationTypeDescriptor = transportationTypeDescriptor;
            this.Etag = etag;
            this.LastModifiedDate = lastModifiedDate;
            this.Ext = ext;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets StudentReference
        /// </summary>
        [DataMember(Name = "studentReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiStudentReference StudentReference { get; set; }

        /// <summary>
        /// Gets or Sets TransportationEducationOrganizationReference
        /// </summary>
        [DataMember(Name = "transportationEducationOrganizationReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiEducationOrganizationReference TransportationEducationOrganizationReference { get; set; }

        /// <summary>
        /// Specific requirements needed to accommodate a student&#39;s physical needs which may include special equipment installed in a vehicle or a special arrangement for transportation.
        /// </summary>
        /// <value>Specific requirements needed to accommodate a student&#39;s physical needs which may include special equipment installed in a vehicle or a special arrangement for transportation.</value>
        [DataMember(Name = "specialAccomodationRequirements", EmitDefaultValue = true)]
        public string SpecialAccomodationRequirements { get; set; }

        /// <summary>
        /// Gets or Sets StudentBusDetails
        /// </summary>
        [DataMember(Name = "studentBusDetails", EmitDefaultValue = false)]
        public EdFiStudentTransportationStudentBusDetails StudentBusDetails { get; set; }

        /// <summary>
        /// The primary type of eligibility for transporting a student at public expense.
        /// </summary>
        /// <value>The primary type of eligibility for transporting a student at public expense.</value>
        [DataMember(Name = "transportationPublicExpenseEligibilityTypeDescriptor", EmitDefaultValue = true)]
        public string TransportationPublicExpenseEligibilityTypeDescriptor { get; set; }

        /// <summary>
        /// The mode or type of transportation utilized by a student to commute to and from school
        /// </summary>
        /// <value>The mode or type of transportation utilized by a student to commute to and from school</value>
        [DataMember(Name = "transportationTypeDescriptor", EmitDefaultValue = true)]
        public string TransportationTypeDescriptor { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// The date and time the resource was last modified.
        /// </summary>
        /// <value>The date and time the resource was last modified.</value>
        [DataMember(Name = "_lastModifiedDate", EmitDefaultValue = false)]
        public DateTime LastModifiedDate { get; set; }

        /// <summary>
        /// Extensions to the StudentTransportation entity.
        /// </summary>
        /// <value>Extensions to the StudentTransportation entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentTransportation {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StudentReference: ").Append(StudentReference).Append("\n");
            sb.Append("  TransportationEducationOrganizationReference: ").Append(TransportationEducationOrganizationReference).Append("\n");
            sb.Append("  SpecialAccomodationRequirements: ").Append(SpecialAccomodationRequirements).Append("\n");
            sb.Append("  StudentBusDetails: ").Append(StudentBusDetails).Append("\n");
            sb.Append("  TransportationPublicExpenseEligibilityTypeDescriptor: ").Append(TransportationPublicExpenseEligibilityTypeDescriptor).Append("\n");
            sb.Append("  TransportationTypeDescriptor: ").Append(TransportationTypeDescriptor).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  LastModifiedDate: ").Append(LastModifiedDate).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SpecialAccomodationRequirements (string) maxLength
            if (this.SpecialAccomodationRequirements != null && this.SpecialAccomodationRequirements.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for SpecialAccomodationRequirements, length must be less than 1024.", new [] { "SpecialAccomodationRequirements" });
            }

            // TransportationPublicExpenseEligibilityTypeDescriptor (string) maxLength
            if (this.TransportationPublicExpenseEligibilityTypeDescriptor != null && this.TransportationPublicExpenseEligibilityTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for TransportationPublicExpenseEligibilityTypeDescriptor, length must be less than 306.", new [] { "TransportationPublicExpenseEligibilityTypeDescriptor" });
            }

            // TransportationTypeDescriptor (string) maxLength
            if (this.TransportationTypeDescriptor != null && this.TransportationTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for TransportationTypeDescriptor, length must be less than 306.", new [] { "TransportationTypeDescriptor" });
            }

            yield break;
        }
    }

}
