/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v73.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// TrackedChangesEdFiLearningStandardEquivalenceAssociationKey
    /// </summary>
    [DataContract(Name = "trackedChanges_edFi_learningStandardEquivalenceAssociationKey")]
    public partial class TrackedChangesEdFiLearningStandardEquivalenceAssociationKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedChangesEdFiLearningStandardEquivalenceAssociationKey" /> class.
        /// </summary>
        /// <param name="varNamespace">The namespace of the organization that has created and owns the association..</param>
        /// <param name="sourceLearningStandardId">The identifier for the specific learning standard (e.g., 111.15.3.1.A)..</param>
        /// <param name="targetLearningStandardId">The identifier for the specific learning standard (e.g., 111.15.3.1.A)..</param>
        public TrackedChangesEdFiLearningStandardEquivalenceAssociationKey(string varNamespace = default, string sourceLearningStandardId = default, string targetLearningStandardId = default)
        {
            this.Namespace = varNamespace;
            this.SourceLearningStandardId = sourceLearningStandardId;
            this.TargetLearningStandardId = targetLearningStandardId;
        }

        /// <summary>
        /// The namespace of the organization that has created and owns the association.
        /// </summary>
        /// <value>The namespace of the organization that has created and owns the association.</value>
        [DataMember(Name = "namespace", EmitDefaultValue = false)]
        public string Namespace { get; set; }

        /// <summary>
        /// The identifier for the specific learning standard (e.g., 111.15.3.1.A).
        /// </summary>
        /// <value>The identifier for the specific learning standard (e.g., 111.15.3.1.A).</value>
        [DataMember(Name = "sourceLearningStandardId", EmitDefaultValue = false)]
        public string SourceLearningStandardId { get; set; }

        /// <summary>
        /// The identifier for the specific learning standard (e.g., 111.15.3.1.A).
        /// </summary>
        /// <value>The identifier for the specific learning standard (e.g., 111.15.3.1.A).</value>
        [DataMember(Name = "targetLearningStandardId", EmitDefaultValue = false)]
        public string TargetLearningStandardId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedChangesEdFiLearningStandardEquivalenceAssociationKey {\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  SourceLearningStandardId: ").Append(SourceLearningStandardId).Append("\n");
            sb.Append("  TargetLearningStandardId: ").Append(TargetLearningStandardId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Namespace (string) maxLength
            if (this.Namespace != null && this.Namespace.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be less than 255.", new [] { "Namespace" });
            }

            // Namespace (string) minLength
            if (this.Namespace != null && this.Namespace.Length < 5)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be greater than 5.", new [] { "Namespace" });
            }

            // SourceLearningStandardId (string) maxLength
            if (this.SourceLearningStandardId != null && this.SourceLearningStandardId.Length > 60)
            {
                yield return new ValidationResult("Invalid value for SourceLearningStandardId, length must be less than 60.", new [] { "SourceLearningStandardId" });
            }

            // TargetLearningStandardId (string) maxLength
            if (this.TargetLearningStandardId != null && this.TargetLearningStandardId.Length > 60)
            {
                yield return new ValidationResult("Invalid value for TargetLearningStandardId, length must be less than 60.", new [] { "TargetLearningStandardId" });
            }

            yield break;
        }
    }

}
