// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v73.Client;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// TrackedChangesEdFiObjectiveAssessmentKey
    /// </summary>
    public partial class TrackedChangesEdFiObjectiveAssessmentKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedChangesEdFiObjectiveAssessmentKey" /> class.
        /// </summary>
        /// <param name="identificationCode">A unique number or alphanumeric code assigned to an objective assessment by a school, school system, a state, or other agency or entity.</param>
        /// <param name="assessmentIdentifier">A unique number or alphanumeric code assigned to an assessment.</param>
        /// <param name="namespace">Namespace for the assessment.</param>
        [JsonConstructor]
        public TrackedChangesEdFiObjectiveAssessmentKey(Option<string?> identificationCode = default, Option<string?> assessmentIdentifier = default, Option<string?> @namespace = default)
        {
            IdentificationCodeOption = identificationCode;
            AssessmentIdentifierOption = assessmentIdentifier;
            NamespaceOption = @namespace;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IdentificationCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdentificationCodeOption { get; private set; }

        /// <summary>
        /// A unique number or alphanumeric code assigned to an objective assessment by a school, school system, a state, or other agency or entity.
        /// </summary>
        /// <value>A unique number or alphanumeric code assigned to an objective assessment by a school, school system, a state, or other agency or entity.</value>
        [JsonPropertyName("identificationCode")]
        public string? IdentificationCode { get { return this.IdentificationCodeOption; } set { this.IdentificationCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessmentIdentifier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssessmentIdentifierOption { get; private set; }

        /// <summary>
        /// A unique number or alphanumeric code assigned to an assessment.
        /// </summary>
        /// <value>A unique number or alphanumeric code assigned to an assessment.</value>
        [JsonPropertyName("assessmentIdentifier")]
        public string? AssessmentIdentifier { get { return this.AssessmentIdentifierOption; } set { this.AssessmentIdentifierOption = new(value); } }

        /// <summary>
        /// Used to track the state of Namespace
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NamespaceOption { get; private set; }

        /// <summary>
        /// Namespace for the assessment.
        /// </summary>
        /// <value>Namespace for the assessment.</value>
        [JsonPropertyName("namespace")]
        public string? Namespace { get { return this.NamespaceOption; } set { this.NamespaceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedChangesEdFiObjectiveAssessmentKey {\n");
            sb.Append("  IdentificationCode: ").Append(IdentificationCode).Append("\n");
            sb.Append("  AssessmentIdentifier: ").Append(AssessmentIdentifier).Append("\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IdentificationCode (string) maxLength
            if (this.IdentificationCode != null && this.IdentificationCode.Length > 60)
            {
                yield return new ValidationResult("Invalid value for IdentificationCode, length must be less than 60.", new [] { "IdentificationCode" });
            }

            // AssessmentIdentifier (string) maxLength
            if (this.AssessmentIdentifier != null && this.AssessmentIdentifier.Length > 60)
            {
                yield return new ValidationResult("Invalid value for AssessmentIdentifier, length must be less than 60.", new [] { "AssessmentIdentifier" });
            }

            // Namespace (string) maxLength
            if (this.Namespace != null && this.Namespace.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be less than 255.", new [] { "Namespace" });
            }

            // Namespace (string) minLength
            if (this.Namespace != null && this.Namespace.Length < 5)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be greater than 5.", new [] { "Namespace" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TrackedChangesEdFiObjectiveAssessmentKey" />
    /// </summary>
    public class TrackedChangesEdFiObjectiveAssessmentKeyJsonConverter : JsonConverter<TrackedChangesEdFiObjectiveAssessmentKey>
    {
        /// <summary>
        /// Deserializes json to <see cref="TrackedChangesEdFiObjectiveAssessmentKey" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TrackedChangesEdFiObjectiveAssessmentKey Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> identificationCode = default;
            Option<string?> assessmentIdentifier = default;
            Option<string?> varNamespace = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "identificationCode":
                            identificationCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assessmentIdentifier":
                            assessmentIdentifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "namespace":
                            varNamespace = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (identificationCode.IsSet && identificationCode.Value == null)
                throw new ArgumentNullException(nameof(identificationCode), "Property is not nullable for class TrackedChangesEdFiObjectiveAssessmentKey.");

            if (assessmentIdentifier.IsSet && assessmentIdentifier.Value == null)
                throw new ArgumentNullException(nameof(assessmentIdentifier), "Property is not nullable for class TrackedChangesEdFiObjectiveAssessmentKey.");

            if (varNamespace.IsSet && varNamespace.Value == null)
                throw new ArgumentNullException(nameof(varNamespace), "Property is not nullable for class TrackedChangesEdFiObjectiveAssessmentKey.");

            return new TrackedChangesEdFiObjectiveAssessmentKey(identificationCode, assessmentIdentifier, varNamespace);
        }

        /// <summary>
        /// Serializes a <see cref="TrackedChangesEdFiObjectiveAssessmentKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiObjectiveAssessmentKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TrackedChangesEdFiObjectiveAssessmentKey trackedChangesEdFiObjectiveAssessmentKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, trackedChangesEdFiObjectiveAssessmentKey, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TrackedChangesEdFiObjectiveAssessmentKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiObjectiveAssessmentKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TrackedChangesEdFiObjectiveAssessmentKey trackedChangesEdFiObjectiveAssessmentKey, JsonSerializerOptions jsonSerializerOptions)
        {
            if (trackedChangesEdFiObjectiveAssessmentKey.IdentificationCodeOption.IsSet && trackedChangesEdFiObjectiveAssessmentKey.IdentificationCode == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiObjectiveAssessmentKey.IdentificationCode), "Property is required for class TrackedChangesEdFiObjectiveAssessmentKey.");

            if (trackedChangesEdFiObjectiveAssessmentKey.AssessmentIdentifierOption.IsSet && trackedChangesEdFiObjectiveAssessmentKey.AssessmentIdentifier == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiObjectiveAssessmentKey.AssessmentIdentifier), "Property is required for class TrackedChangesEdFiObjectiveAssessmentKey.");

            if (trackedChangesEdFiObjectiveAssessmentKey.NamespaceOption.IsSet && trackedChangesEdFiObjectiveAssessmentKey.Namespace == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiObjectiveAssessmentKey.Namespace), "Property is required for class TrackedChangesEdFiObjectiveAssessmentKey.");

            if (trackedChangesEdFiObjectiveAssessmentKey.IdentificationCodeOption.IsSet)
                writer.WriteString("identificationCode", trackedChangesEdFiObjectiveAssessmentKey.IdentificationCode);

            if (trackedChangesEdFiObjectiveAssessmentKey.AssessmentIdentifierOption.IsSet)
                writer.WriteString("assessmentIdentifier", trackedChangesEdFiObjectiveAssessmentKey.AssessmentIdentifier);

            if (trackedChangesEdFiObjectiveAssessmentKey.NamespaceOption.IsSet)
                writer.WriteString("namespace", trackedChangesEdFiObjectiveAssessmentKey.Namespace);
        }
    }
}
