// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v73.Client;

namespace EdFi.OdsApi.Sdk.v73.Models.All
{
    /// <summary>
    /// TrackedChangesEdFiCrisisEventKey
    /// </summary>
    public partial class TrackedChangesEdFiCrisisEventKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedChangesEdFiCrisisEventKey" /> class.
        /// </summary>
        /// <param name="crisisEventName">The name of the crisis event that occurred. If there is no generally accepted name for this crisis event, the suggested format: Location + Crisis type + Year.</param>
        [JsonConstructor]
        public TrackedChangesEdFiCrisisEventKey(Option<string?> crisisEventName = default)
        {
            CrisisEventNameOption = crisisEventName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CrisisEventName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CrisisEventNameOption { get; private set; }

        /// <summary>
        /// The name of the crisis event that occurred. If there is no generally accepted name for this crisis event, the suggested format: Location + Crisis type + Year.
        /// </summary>
        /// <value>The name of the crisis event that occurred. If there is no generally accepted name for this crisis event, the suggested format: Location + Crisis type + Year.</value>
        [JsonPropertyName("crisisEventName")]
        public string? CrisisEventName { get { return this.CrisisEventNameOption; } set { this.CrisisEventNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedChangesEdFiCrisisEventKey {\n");
            sb.Append("  CrisisEventName: ").Append(CrisisEventName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CrisisEventName (string) maxLength
            if (this.CrisisEventName != null && this.CrisisEventName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CrisisEventName, length must be less than 100.", new [] { "CrisisEventName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TrackedChangesEdFiCrisisEventKey" />
    /// </summary>
    public class TrackedChangesEdFiCrisisEventKeyJsonConverter : JsonConverter<TrackedChangesEdFiCrisisEventKey>
    {
        /// <summary>
        /// Deserializes json to <see cref="TrackedChangesEdFiCrisisEventKey" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TrackedChangesEdFiCrisisEventKey Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> crisisEventName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "crisisEventName":
                            crisisEventName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (crisisEventName.IsSet && crisisEventName.Value == null)
                throw new ArgumentNullException(nameof(crisisEventName), "Property is not nullable for class TrackedChangesEdFiCrisisEventKey.");

            return new TrackedChangesEdFiCrisisEventKey(crisisEventName);
        }

        /// <summary>
        /// Serializes a <see cref="TrackedChangesEdFiCrisisEventKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiCrisisEventKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TrackedChangesEdFiCrisisEventKey trackedChangesEdFiCrisisEventKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, trackedChangesEdFiCrisisEventKey, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TrackedChangesEdFiCrisisEventKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiCrisisEventKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TrackedChangesEdFiCrisisEventKey trackedChangesEdFiCrisisEventKey, JsonSerializerOptions jsonSerializerOptions)
        {
            if (trackedChangesEdFiCrisisEventKey.CrisisEventNameOption.IsSet && trackedChangesEdFiCrisisEventKey.CrisisEventName == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiCrisisEventKey.CrisisEventName), "Property is required for class TrackedChangesEdFiCrisisEventKey.");

            if (trackedChangesEdFiCrisisEventKey.CrisisEventNameOption.IsSet)
                writer.WriteString("crisisEventName", trackedChangesEdFiCrisisEventKey.CrisisEventName);
        }
    }
}
